### ISSUE TITLE
Хедер

### ISSUE THREAD

**Issue by slikNET** [slikNET/KEYZ#36]
1) http://take.ms/24UNk
(main-slider нада min-height)

2) http://take.ms/n7EGk через меню стрілка на слайдері не нажимається

**Comment by perchitos** [comment]
1.  min-height на нього не діє, я пробувала і враперу давати, і слайдеру, і внутнішньому контейнеру

2.  меню з самого початку і робила як в минулому проекті - width: 265px i right: -265px, але якось криво зробила і з'являвся нижній скролл
(oh враперу теж задала але толку 0)

**Comment by slikNET** [comment]
1) sliders options:{  inherit_height_from  }

2) .wrapper {    position: relative;}
.menu { right: -215px; }
