### ISSUE TITLE
Головний слайдер

### ISSUE THREAD

**Issue by slikNET** [slikNET/KEYZ#43]
1) http://take.ms/JWLYR
зроби трошки менший падінг на моб.

2) http://take.ms/lbDNW - 	BACK TO RESULTS на моб. версію в ліву сторону
3) чому в тебе на одних сторінках є білий фон а на інших - нема (я создав пункт про нечитабельність)

**Comment by perchitos** [comment]
1. зменшила min-height: 450px; для слайдера і content-top

2. можна забрати флоат, але коли воно справа то гарніше і не зліплене все в купу

3. виправила
