### ISSUE TITLE
Відео

### ISSUE THREAD

**Issue by slikNET** [slikNET/KEYZ#63]
http://take.ms/Pupau - чого воно в тебе на моб. версії перекидує на другий сайт а не попап ?

**Comment by perchitos** [comment]
Не знаю, думала так має бути
коли захожу з телефону то перекидає в ютуб

**Comment by slikNET** [comment]
думаєш?

**Comment by perchitos** [comment]
Мені здається так і краще, бо попап на малих екранах мені не комільфо, а на ютубі всі сидять і шарять що до чого

**Comment by slikNET** [comment]
ну ок
